# get url
# Cookie: 


post http://localhost:3000/order/add
Content-Type: application/json
Cookie:  access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzFiYTdmMzMyZGRhYjQ1ZmM2MjM2ZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzIzOTcyMjcxLCJleHAiOjE3MjY1NjQyNzF9.ZCu8vrv-MKHiogn5ibYAyIfSw2QGxmIrEpjANdOwNAw; Path=/; HttpOnly; Secure; SameSite=None

{
"totalPrice":15,
"numberOfItems":30,
"shippingAddress":"zabutinski 20 bney bnerak",
"cashierName":"kobi"
}